language: python
sudo: false
dist: trusty

python:
   - 3.5
   - 3.6

cache: pip

git:
  depth: 1

env:
   - xversion=1.0 oob=0 post=0
   - xversion=1.0 oob=0 post=1

   - xversion=2.0 oob=1 post=1
   - xversion=2.0 oob=1 post=0

   - xversion=2.0 oob=0 post=1
   - xversion=2.0 oob=0 post=0

   - xversion=3.0 oob=1 post=1
   - xversion=3.0 oob=1 post=0

   - xversion=3.0 oob=0 post=1
   - xversion=3.0 oob=0 post=0

install:
   - pip install .
   - wget https://github.com/orf/xcat_app/releases/download/0.2/xcat-app-jar-with-dependencies.jar
   - wget https://github.com/orf/xcat_app/releases/download/0.2/database.xml
   - wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
   - chmod +x wait-for-it.sh

script:
   - java -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -jar xcat-app-jar-with-dependencies.jar &
   - SERVER_PID=$!
   - SERVER=http://localhost:4567/
   - ./wait-for-it.sh localhost:4567
   - xcat --help
   - xcat detectip
   - if [ "oob" = "1" ]; then OOB_FLAG='--oob-ip=localhost'; fi
   - if [ "oob" = "1" ]; then POST_FLAG='--body --method=POST'; fi

   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG $POST_FLAG
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG $POST_FLAG --features --concurrency=1
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG $POST_FLAG --features
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG $POST_FLAG --fast
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG $POST_FLAG --cookie=abc
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG $POST_FLAG --shellcmd="help"